#!/usr/bin/env python3
import json
import os
import stat
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse
import subprocess

BASE_DIR = Path(__file__).resolve().parent
ROOT_DIR = BASE_DIR
ENV_PATH = ROOT_DIR / ".desk-sprite.env"
UI_DIR = ROOT_DIR.parent / "media"
PROMPTS_PATH = ROOT_DIR / "console_config.json"
RESTART_SCRIPT = ROOT_DIR.parent / "restart-desk-pet.command"
MAX_REQUEST_BYTES = 64 * 1024
LOOPBACK_HOSTS = {"127.0.0.1", "localhost", "::1"}
ENV_KEYS = [
    "OPENCLAW_ROOT",
    "OPENCLAW_GATEWAY_URL",
    "OPENCLAW_GATEWAY_TOKEN",
    "OPENCLAW_ACTIVE_WINDOW_SECONDS",
    "OPENCLAW_START_SCRIPT",
]

DEFAULT_QUICK_PROMPTS = [
    "查个天气吧~",
    "看下最新的前沿 AI 消息",
    "自我进化",
    "换一个快的大模型！",
    "看看有没有新版本？",
    "检查下这两天的重要邮件。",
    "给朋友发消息，通知已经遛狗了！",
]


def _single_line(value: object, field: str) -> str:
    text = str(value or "").strip()
    if any(char in text for char in ("\x00", "\r", "\n")):
        raise ValueError(f"{field} must be a single-line value")
    return text


def validate_config(config: dict) -> dict:
    if not isinstance(config, dict):
        raise ValueError("config must be an object")

    cleaned = {key: _single_line(config.get(key, ""), key) for key in ENV_KEYS}
    gateway_url = cleaned["OPENCLAW_GATEWAY_URL"]
    if gateway_url:
        parsed = urlparse(gateway_url)
        if parsed.scheme not in {"ws", "wss"} or not parsed.hostname:
            raise ValueError("OPENCLAW_GATEWAY_URL must use ws:// or wss://")

    active_window = cleaned["OPENCLAW_ACTIVE_WINDOW_SECONDS"]
    if active_window:
        try:
            seconds = float(active_window)
        except ValueError as exc:
            raise ValueError("OPENCLAW_ACTIVE_WINDOW_SECONDS must be numeric") from exc
        if not 1 <= seconds <= 3600:
            raise ValueError("OPENCLAW_ACTIVE_WINDOW_SECONDS must be between 1 and 3600")

    start_script = cleaned["OPENCLAW_START_SCRIPT"]
    if start_script and not Path(start_script).is_absolute():
        raise ValueError("OPENCLAW_START_SCRIPT must be an absolute path")
    return cleaned


def _host_and_port(value: str):
    try:
        parsed = urlparse(f"//{value}")
        return (parsed.hostname or "").lower(), parsed.port
    except ValueError:
        return "", None


def host_is_allowed(host_header: str, server_port: int) -> bool:
    host, port = _host_and_port(host_header)
    return host in LOOPBACK_HOSTS and (port is None or port == server_port)


def origin_is_allowed(origin: str, fetch_site: str, server_port: int) -> bool:
    normalized_site = (fetch_site or "").lower()
    if normalized_site in {"cross-site", "same-site"}:
        return False
    if not origin:
        return normalized_site in {"", "none", "same-origin"}
    try:
        parsed = urlparse(origin)
        port = parsed.port or (443 if parsed.scheme == "https" else 80)
    except ValueError:
        return False
    return (
        parsed.scheme in {"http", "https"}
        and (parsed.hostname or "").lower() in LOOPBACK_HOSTS
        and port == server_port
    )


def load_env(path: Path) -> dict:
    if not path.exists():
        return {}
    data = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        data[key] = value
    return data


def save_env(path: Path, data: dict) -> None:
    lines = [
        "# Generated by desk-sprite console",
        "",
    ]
    for key in ENV_KEYS:
        value = _single_line(data.get(key, ""), key)
        if not value:
            continue
        if key == "OPENCLAW_ACTIVE_WINDOW_SECONDS":
            lines.append(f"{key}={value}")
        else:
            lines.append(f'{key}="{value}"')
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)


def load_prompts() -> list:
    if not PROMPTS_PATH.exists():
        save_prompts(DEFAULT_QUICK_PROMPTS)
        return DEFAULT_QUICK_PROMPTS[:]
    try:
        raw = json.loads(PROMPTS_PATH.read_text(encoding="utf-8"))
        values = raw.get("quickPrompts", [])
        if not isinstance(values, list):
            return []
        cleaned = []
        seen = set()
        for item in values:
            text = str(item).strip()
            if not text or text in seen:
                continue
            seen.add(text)
            cleaned.append(text)
        if not cleaned:
            save_prompts(DEFAULT_QUICK_PROMPTS)
            return DEFAULT_QUICK_PROMPTS[:]
        return cleaned
    except Exception:
        return DEFAULT_QUICK_PROMPTS[:]


def save_prompts(values: list) -> None:
    cleaned = []
    seen = set()
    for item in values:
        text = str(item).strip()
        if not text or text in seen:
            continue
        seen.add(text)
        cleaned.append(text)
    payload = {"quickPrompts": cleaned}
    PROMPTS_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def detect_openclaw_roots() -> list:
    home = Path.home()
    configured_root = os.environ.get("OPENCLAW_ROOT", "").strip()
    candidates = ([Path(configured_root)] if configured_root else []) + [
        home / ".openclaw",
        home / "Openclaw_Workspace",
        home / "OpenClaw",
        home / "Openclaw",
    ]
    roots = []
    seen = set()
    for path in candidates:
        if not path or str(path) in seen:
            continue
        seen.add(str(path))
        if not path.exists():
            continue
        roots.append(str(path))
    return roots


class ConsoleHandler(SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header("Cache-Control", "no-store")
        self.send_header("Content-Security-Policy", "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'")
        self.send_header("Cross-Origin-Resource-Policy", "same-origin")
        self.send_header("Permissions-Policy", "camera=(), microphone=(), geolocation=()")
        self.send_header("Referrer-Policy", "no-referrer")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("X-Frame-Options", "DENY")
        super().end_headers()

    def _send_json(self, payload, code=200):
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _read_json(self):
        content_type = self.headers.get("Content-Type", "").split(";", 1)[0].strip().lower()
        if content_type != "application/json":
            raise ValueError("Content-Type must be application/json")
        try:
            length = int(self.headers.get("Content-Length", "0"))
        except ValueError as exc:
            raise ValueError("Invalid Content-Length") from exc
        if length < 0 or length > MAX_REQUEST_BYTES:
            raise ValueError("Request body is too large")
        raw = self.rfile.read(length) if length else b""
        if not raw:
            return {}
        return json.loads(raw.decode("utf-8"))

    def do_GET(self):
        if not host_is_allowed(self.headers.get("Host", ""), self.server.server_address[1]):
            return self._send_json({"ok": False, "error": "Forbidden host"}, code=403)
        parsed = urlparse(self.path)
        if parsed.path == "/api/config":
            env = load_env(ENV_PATH)
            payload = {
                "config": {
                    "OPENCLAW_ROOT": env.get("OPENCLAW_ROOT", ""),
                    "OPENCLAW_GATEWAY_URL": env.get("OPENCLAW_GATEWAY_URL", "ws://127.0.0.1:18789"),
                    "OPENCLAW_GATEWAY_TOKEN": env.get("OPENCLAW_GATEWAY_TOKEN", ""),
                    "OPENCLAW_ACTIVE_WINDOW_SECONDS": env.get("OPENCLAW_ACTIVE_WINDOW_SECONDS", ""),
                    "OPENCLAW_START_SCRIPT": env.get("OPENCLAW_START_SCRIPT", ""),
                },
                "quickPrompts": load_prompts(),
                "detectedRoots": detect_openclaw_roots(),
                "assetsDir": str(UI_DIR),
                "envPath": str(ENV_PATH),
            }
            return self._send_json(payload)

        return super().do_GET()

    def do_POST(self):
        server_port = self.server.server_address[1]
        if not host_is_allowed(self.headers.get("Host", ""), server_port):
            return self._send_json({"ok": False, "error": "Forbidden host"}, code=403)
        if not origin_is_allowed(
            self.headers.get("Origin", ""),
            self.headers.get("Sec-Fetch-Site", ""),
            server_port,
        ):
            return self._send_json({"ok": False, "error": "Forbidden origin"}, code=403)
        parsed = urlparse(self.path)
        if parsed.path == "/api/restart":
            if not RESTART_SCRIPT.exists():
                return self._send_json({"ok": False, "error": "restart script not found"}, code=404)
            try:
                subprocess.Popen(
                    ["/bin/zsh", str(RESTART_SCRIPT)],
                    cwd=str(RESTART_SCRIPT.parent),
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    start_new_session=True,
                )
                return self._send_json({"ok": True})
            except Exception as exc:
                return self._send_json({"ok": False, "error": str(exc)}, code=500)
        if parsed.path == "/api/pick-root":
            try:
                script = 'POSIX path of (choose folder with prompt "选择 OpenClaw 状态目录")'
                output = subprocess.check_output(["osascript", "-e", script], stderr=subprocess.STDOUT)
                path = output.decode("utf-8").strip()
                return self._send_json({"ok": True, "path": path})
            except subprocess.CalledProcessError as exc:
                message = exc.output.decode("utf-8", errors="ignore").strip()
                return self._send_json({"ok": False, "error": message or "cancelled"})
            except Exception as exc:
                return self._send_json({"ok": False, "error": str(exc)})
        if parsed.path != "/api/config":
            return self._send_json({"ok": False, "error": "Not found"}, code=404)
        try:
            data = self._read_json()
            config = validate_config(data.get("config", {}) if isinstance(data, dict) else {})
            prompts = data.get("quickPrompts", []) if isinstance(data, dict) else []
            save_env(ENV_PATH, config)
        except (UnicodeDecodeError, json.JSONDecodeError, ValueError) as exc:
            return self._send_json({"ok": False, "error": str(exc)}, code=400)
        if isinstance(prompts, list):
            save_prompts(prompts)
        return self._send_json({"ok": True})

    def do_OPTIONS(self):
        return self._send_json({"ok": False, "error": "Method not allowed"}, code=405)


def main():
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=int(os.environ.get("DESK_SPRITE_CONSOLE_PORT", "17890")))
    args = parser.parse_args()

    os.chdir(str(ROOT_DIR / "console"))
    server = ThreadingHTTPServer(("127.0.0.1", args.port), ConsoleHandler)
    print(f"[desk-sprite] console running on http://127.0.0.1:{args.port}/")
    server.serve_forever()


if __name__ == "__main__":
    main()
